### ISSUE TITLE
download_and_preprocess_data() does not work

### ISSUE THREAD

**Issue by AlexSiXiong** [dsgiitr/d2l-pytorch#107]
Hi authors, 

it seems that download_and_preprocess_data() method does not work?

can you check?

Thanks

**Comment by suvaansh** [comment]
Could you please post the error you're getting and the file name containing the function?

**Comment by AlexSiXiong** [comment]
![image](https://user-images.githubusercontent.com/52727136/85472362-db62d300-b605-11ea-83a6-9f6f4d4afe69.png)

**Comment by suvaansh** [comment]
This is the link for the function:
https://github.com/dsgiitr/d2l-pytorch/blob/9a2b9f31e5933f89e3ed9d8fb5ffd38a9fc3900d/d2l/ssd_utils.py#L310

Can you please tell the name of the notebook you're using?

**Comment by AlexSiXiong** [comment]
Single Shot Multibox Detection (SSD)


https://github.com/dsgiitr/d2l-pytorch/blob/master/Ch14_Computer_Vision/Single_Shot_Multibox_Detection.ipynb

**Comment by AlexSiXiong** [comment]
is this that you are talking about?

**Comment by suvaansh** [comment]
This function requires MXNet for converting the .rec files to .png images.
So we have already downloaded the dataset and saved the processed data in the folder: https://github.com/dsgiitr/d2l-pytorch/tree/master/data/pikachu

You can directly use the preprocessed data from this folder.
Or you can use the function download_and_preprocess_data() by installing MXNet

**Comment by suvaansh** [comment]
The RecordIO format in which the dataset is downloaded is not available in PyTorch. So you need MXNet to use this function.

**Comment by AlexSiXiong** [comment]
Thanks for the data, and I can use it directly.

Just asking, I have tried like this... and it does not work

![image](https://user-images.githubusercontent.com/52727136/85475188-d30c9700-b609-11ea-9dab-1489f01b7fe3.png)

**Comment by suvaansh** [comment]
It's not an inbuilt function of MXNet.

You can try importing this file : https://github.com/dsgiitr/d2l-pytorch/blob/master/d2l/ssd_utils.py
And then call the function "download_and_preprocess_data()" directly which is present in the file

**Comment by AlexSiXiong** [comment]
got you, thank you very much
