### ISSUE TITLE
A new idea for implementation during summers.

### ISSUE THREAD

**Issue by ujjawalsharma15** [dsgiitr/d2l-pytorch#2]
We can implement functions like tensor rotation, scaling, translation, general and channel-wise etc,
which are currently not possible with direct use of pytorch library as there are no such direct functions implemented, one idea was to convert tensor to PIL image and apply transformations and then revert back to tensor, the idea seems legit but there seems to be a bug in the library that doesn't return the correct result after conversion back to tensor, so such custom functions can be very helpful.

**Comment by AnirudhDagar** [comment]
Seems good. Closing this. Interested may contribute. Irrelevant here.
