### ISSUE TITLE
Implement `d2l.train_ch3()`

### ISSUE THREAD

**Issue by aksub99** [dsgiitr/d2l-pytorch#4]
To exactly replicate the book, function `d2l.train_ch3()` function would be a necessary addition. This function is to be called during training from the implementations in other chapters as well. This would be more convenient than writing the training loop each and every time.
Infact, all training loops required in the book can be added to `train.py` similar to https://github.com/d2l-ai/d2l-en/blob/8e53fce19c6c744cf4994a896c43e382567e6fbc/d2l/train.py#L1

**Comment by AnirudhDagar** [comment]
Yeah! This was discussed in the last meet. For example, look at [this](https://github.com/dsgiitr/d2l-pytorch/blob/master/d2l/data/fashion_mnist.py) script, this is a pytorch replica of the original one and is used in later sections of the book like you pointed out. So if you create a section notebook which calls a particular function from the d2l package, then please implement that and add it there (in a similar manner as the original book does)as well for future use, if it is not present already.

**Comment by aksub99** [comment]
I'll submit a PR implementing `d2l.train_ch3()` soon. It would be great if this issue could be assigned to me.
