### ISSUE TITLE
ready for social attention?

### ISSUE THREAD

**Issue by soumith** [dsgiitr/d2l-pytorch#72]
Hey, really great work on porting the book's code over to PyTorch.

It's one of the nicest books I read (atleast the few chapters I did) and Zack & team are great writers.

We want to get this port some attention via PyTorch Twitter, and want to make sure this book is ready in a state that you like -- and that we aren't surprising you by pre-announcing.

Let us know

**Comment by AnirudhDagar** [comment]
Hi Soumith, can’t thank you enough for appreciating our work.

The project is almost in its final stage and the team is continuously working on it. Also, we are expecting a lot more contributions in the future from the community.
 
It would be great if you could share it via PyTorch Twitter. <3

**Comment by soumith** [comment]
great, will tweet tomorrow

**Comment by AnirudhDagar** [comment]
Hi @soumith we'll try to wrap up this project in the next month. I guess you forgot to tweet about the project. Would it be ok if we submit it in [Global PyTorch Summer Hackathon](https://pytorch.devpost.com/)

**Comment by soumith** [comment]
sorry, i think i kept the browser tab open to tweet at the right time, but browser crashed, and then i forgot about it. will line it up for the next window.
If it goes with the rules of the hackathon, yes. I believe the hackathon accounts contribution in the hackathon time-period.

**Comment by soumith** [comment]
https://twitter.com/PyTorch/status/1166356768978591744
