### ISSUE TITLE
Can I find the answer of the practising problems in somewhere?

### ISSUE THREAD

**Issue by cupcakefromchina** [dsgiitr/d2l-pytorch#90]
Can I find the answer of the practising problems in somewhere?

**Comment by AnirudhDagar** [comment]
Unfortunately, there is no single repository for all the answers. I'll suggest you to google stuff and find out answers or start a thread in the [MXNet Forums](https://discuss.mxnet.io/) / [PyTorch Forums](https://discuss.pytorch.org/). You may open up issues in the original [GitHub repository](https://github.com/d2l-ai/d2l-en) or here of it is PyTorch specific.
