### ISSUE TITLE
errors on chapter of Implementation of Multilayer Perceptron from Scratch

### ISSUE THREAD

**Issue by CaiyuZhang** [dsgiitr/d2l-pytorch#94]

**Comment by suvaansh** [comment]
You need to install opencv3 for this module. You can download from "https://opencv.org/" depending upon your operating system.
Or you can comment this line (from .ssd_utils import *) in "~\Desktop\d2l-pytorch-master\d2l-pytorch-master\d2l_init_.py" for now. This is not required for the Implementation of Multilayer Perceptron from Scratch but is required for the Object detection notebooks.

**Comment by CaiyuZhang** [comment]
> You need to install opencv3 for this module. You can download from "https://opencv.org/" depending upon your operating system.
> Or you can comment this line (from .ssd_utils import *) in "~\Desktop\d2l-pytorch-master\d2l-pytorch-master\d2l_init_.py" for now. This is not required for the Implementation of Multilayer Perceptron from Scratch but is required for the Object detection notebooks.

Thank u man!!!!
